rows:
  - columns:
    - entries:
      - type: header
        header:
          title: 
            text: "Nexmo ❤️ Community"
            align: center
          icon:
            name: icon-world-hand
            color: blue
  - columns:
    - entries:
      - type: line_divider
  - columns:
    - entries:
      - type: section_header
        section_header:
          title: "You can find us at these upcoming events"
          icon:
            name: icon-group-7
            color: blue
  - columns:
    - entries:
      - type: events
  - columns:
    - entries:
      - type: line_divider
  - columns:
    - entries:
      - type: section_header
        section_header:
          title: "Resources"
          icon:
            name: icon-menu
            color: blue
  - columns:
    - entries:
      - type: featured_session
  - columns:
    - entries:
      - type: sessions
  - columns:
    - entries:
      - type: line_divider
  - columns:
    - entries:
      - type: contact_support
      - type: line_divider
      - type: join_slack
    - entries:
      - type: section_header
        section_header:
          title: "@NexmoDev on Twitter"
          icon:
            name: Brand-icon-twitter
            color: blue
      - type: html
        html:
          content: <a class="twitter-timeline" data-width="400" data-height="300" data-dnt="true" href="https://twitter.com/NexmoDev?ref_src=twsrc%5Etfw">Tweets by NexmoDev</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
